In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])


In [14]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.random.rand(3, 2)

array([[0.11040497, 0.7562967 ],
       [0.38095298, 0.31032488],
       [0.0328485 , 0.95679895]])

In [20]:
np.random.randn(3, 2)

array([[-1.93414847,  0.62930909],
       [-1.07059518, -1.23867088],
       [ 0.2899139 , -0.56068795]])

Array Attributes



In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
print(arr.shape)

(2, 3)


In [23]:
print(arr.ndim)

2


In [24]:
print(arr.size)

6


In [25]:
print(arr.dtype)

int64


Array Operations

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])




array([0.84147098, 0.90929743, 0.14112001])

In [28]:
a + b


array([5, 7, 9])

In [29]:
a * b


array([ 4, 10, 18])

In [30]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

Matrix Multiplication

In [31]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


In [32]:
np.dot(A, B)



array([[19, 22],
       [43, 50]])

In [33]:
A @ B

array([[19, 22],
       [43, 50]])

Aggregation

In [34]:
arr = np.array([1, 2, 3, 4])



In [35]:
arr.sum()


np.int64(10)

In [36]:
arr.mean()


np.float64(2.5)

In [37]:
arr.max()


np.int64(4)

In [38]:
arr.min()


np.int64(1)

In [40]:
arr.std()

np.float64(1.118033988749895)

Indexing & Slicing

In [42]:
arr = np.array([1, 2, 3, 4, 5])



In [43]:
arr[0]

np.int64(1)

In [44]:
arr[1:4]

array([2, 3, 4])

In [45]:
arr[::2]

array([1, 3, 5])

In [50]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [48]:
arr[0, 1]


np.int64(2)

In [49]:
arr[:, 1]


array([2, 5])

In [51]:
arr[1, :2]

array([4, 5])

Boolean Indexing

In [52]:
arr = np.array([1, 2, 3, 4, 5])



In [55]:
mask = arr > 3


In [54]:
arr[mask]

array([4, 5])

Reshaping & Combining Arrays

Reshaping

In [58]:
arr = np.arange(6)

In [57]:
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

Concatenation

In [59]:
a = np.array([1, 2])
b = np.array([3, 4])


In [60]:
np.concatenate((a, b))

array([1, 2, 3, 4])

Stacking

In [61]:
np.vstack((a, b))



array([[1, 2],
       [3, 4]])

In [62]:
np.hstack((a, b))

array([1, 2, 3, 4])

Broadcasting

In [64]:
a = np.array([1, 2, 3])



In [65]:
a + 5  # [6, 7, 8]

array([6, 7, 8])

Saving & Loading Arrays

In [66]:
np.save('array.npy', arr)

In [67]:
loaded_arr = np.load('array.npy')